[package]
name = "mediator-b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.19.0"
reqwest = { version = "0.12.4", features = ["json", "multipart", "blocking"] }
hex-literal = "0.4.1"
tokio = { version = "1.37.0", features = ["full"] }
sha2 = "0.10.8"
serde = { version = "1.0.203", features = ["derive"] }
rsa = "0.9.6"
rand = "0.8.4"
base64 = "0.22.1"
serde_json = "1.0.117"
notify = "7.0.0"
chrono = "0.4.39"
regex = "1.11.1"
thiserror = "2.0.10"
serde_yaml = "0.9"

[profile.release]
strip = true
lto = true
codegen-units = 1
