version: "3.8"

services:
  mediator-owner-1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./settings:/app/settings
      - ./scripts:/app/scripts
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - target-1:/app/target
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /app
    entrypoint: ["cargo", "run"]
  
  mediator-owner-2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./settings:/app/settings
      - ./scripts:/app/scripts
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - target-2:/app/target
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /app
    entrypoint: ["cargo", "run"]

volumes:
  target-1:
  target-2: