/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IoTMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMerchandise"
      | "getMerchandises"
      | "registerMerchandise"
      | "s_merchandises"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMerchandise",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerchandises",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerMerchandise",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "s_merchandises",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMerchandise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerchandises",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMerchandise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_merchandises",
    data: BytesLike
  ): Result;
}

export interface IoTMarket extends BaseContract {
  connect(runner?: ContractRunner | null): IoTMarket;
  waitForDeployment(): Promise<this>;

  interface: IoTMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMerchandise: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getMerchandises: TypedContractMethod<[], [string[]], "view">;

  registerMerchandise: TypedContractMethod<
    [merchandise: AddressLike],
    [void],
    "nonpayable"
  >;

  s_merchandises: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMerchandise"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMerchandises"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "registerMerchandise"
  ): TypedContractMethod<[merchandise: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "s_merchandises"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  filters: {};
}
