/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PubKeyInterface extends Interface {
  getFunction(nameOrSignature: "getPubKey" | "registerKey"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPubKey",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "registerKey", values: [string]): string;

  decodeFunctionResult(functionFragment: "getPubKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerKey",
    data: BytesLike
  ): Result;
}

export interface PubKey extends BaseContract {
  connect(runner?: ContractRunner | null): PubKey;
  waitForDeployment(): Promise<this>;

  interface: PubKeyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPubKey: TypedContractMethod<[who: AddressLike], [string], "view">;

  registerKey: TypedContractMethod<[pubKey: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPubKey"
  ): TypedContractMethod<[who: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerKey"
  ): TypedContractMethod<[pubKey: string], [void], "nonpayable">;

  filters: {};
}
