load_module modules/ngx_rtmp_module.so;
load_module modules/ngx_http_js_module.so;
error_log stderr info;

user root;
events {}
rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        application live {
            live on;
            on_publish 127.0.0.1:5024/verify;
            on_play 127.0.0.1:5024/verify;
            allow publish all;
            allow play all;
            recorder split {
                record video;
                record_path /tmp;
                record_suffix _%Y%m%d_%H%M.flv;
                record_interval 1m;
                
                exec_record_done /scripts/count.sh $path /recordings/$basename.mp4;
            }
        }
    }
}

http {
    js_path /;
    js_import auth from auth.js;
    js_shared_dict_zone zone=keys:128K state=/tmp/dict.json;
    server {
        #register
        listen 5024;
        location /register {
            js_content auth.register;
        }
        location /verify {
            allow 127.0.0.1;
            deny all;
            js_content auth.verify;
        }
    }
}
